# Generated by Django 4.2.10 on 2025-03-22 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('face', 'Face Violation'), ('sound', 'Sound Violation'), ('navigation', 'Navigation Violation')], max_length=50)),
                ('alert_time', models.DateTimeField(auto_now_add=True)),
                ('alert_description', models.TextField(blank=True, help_text='Description of the alert')),
                ('action_taken', models.CharField(blank=True, choices=[('none', 'None'), ('warn', 'Warn Student'), ('terminate', 'Terminate Exam'), ('resume', 'Resume Exam')], default='none', help_text='Action taken by the proctor in response to the alert', max_length=20)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='student.attempt')),
                ('proctor', models.ForeignKey(limit_choices_to={'user_type': 'proctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
