# Generated by Django 4.2.10 on 2025-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the exam', null=True),
        ),
    ]
