# Generated by Django 4.2.10 on 2025-03-22 01:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_media', models.FileField(blank=True, null=True, upload_to='question_media/')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('SA', 'Short Answer')], max_length=20)),
                ('choiceA', models.CharField(blank=True, max_length=255, null=True)),
                ('choiceB', models.CharField(blank=True, max_length=255, null=True)),
                ('choiceC', models.CharField(blank=True, max_length=255, null=True)),
                ('choiceD', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma separated list of keywords')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='proctor.exam')),
            ],
        ),
    ]
