# Generated by Django 4.2.10 on 2025-03-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctor', '0002_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the exam ex: 2:30:00', null=True),
        ),
    ]
